import { 
  FaLaptop, 
  FaMobileAlt, 
  FaTv, 
  FaTshirt, 
  FaRunning, 
  FaCouch, 
  FaGem, 
  FaHeartbeat,
  FaBookOpen
} from 'react-icons/fa';

export const categories = [
  {
    id: 'electronics',
    name: 'Electronics',
    icon: FaLaptop,
    image: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg',
    path: '/products?category=electronics'
  },
  {
    id: 'mobiles',
    name: 'Mobiles',
    icon: FaMobileAlt,
    image: 'https://m.media-amazon.com/images/I/71d7rfSl0wL._AC_SL1500_.jpg',
    path: '/products?category=mobiles'
  },
  {
    id: 'laptops',
    name: 'Laptops',
    icon: FaLaptop,
    image: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg',
    path: '/products?category=laptops'
  },
  {
    id: 'men-fashion',
    name: "Men's Fashion",
    icon: FaTshirt,
    image: 'https://m.media-amazon.com/images/I/61Nl8q4lV2L._AC_UL1500_.jpg',
    path: '/products?category=men-fashion'
  },
  {
    id: 'women-fashion',
    name: "Women's Fashion",
    icon: FaTshirt,
    image: 'https://m.media-amazon.com/images/I/71Y32K55BqL._AC_UL1500_.jpg',
    path: '/products?category=women-fashion'
  },
  {
    id: 'footwear',
    name: 'Footwear',
    icon: FaRunning,
    image: 'https://m.media-amazon.com/images/I/71D9ImsvEtL._AC_UY695_.jpg',
    path: '/products?category=footwear'
  },
  {
    id: 'home-kitchen',
    name: 'Home & Kitchen',
    icon: FaCouch,
    image: 'https://m.media-amazon.com/images/I/81BDBKkQ4AL._AC_SL1500_.jpg',
    path: '/products?category=home-kitchen'
  },
  {
    id: 'beauty',
    name: 'Beauty',
    icon: FaGem,
    image: 'https://m.media-amazon.com/images/I/61S7PBB9g9L._SL1500_.jpg',
    path: '/products?category=beauty'
  },
  {
    id: 'sports',
    name: 'Sports',
    icon: FaRunning,
    image: 'https://m.media-amazon.com/images/I/71Xm3Q+-l+L._AC_SL1500_.jpg',
    path: '/products?category=sports'
  }
];

export const products = [
  {
    "_id": "p1",
    "name": "iPhone 15 Pro Max (256GB, Natural Titanium)",
    "brand": "Apple",
    "category": "Electronics",
    "subcategory": "Mobiles",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+10",
    "description": "Experience titanium design, ground-breaking A17 Pro chip, customisable Action button, and the most powerful iPhone camera system ever.",
    "price": 119900,
    "discountPercentage": 8.3,
    "discountPrice": 109900,
    "rating": 4.9,
    "numReviews": 832,
    "stock": 15,
    "tag": "trending"
  },
  {
    "_id": "p2",
    "name": "Samsung Galaxy S24 Ultra (512GB, Titanium Gray)",
    "brand": "Samsung",
    "category": "Electronics",
    "subcategory": "Mobiles",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+11",
    "description": "Welcome to the era of mobile AI. With Galaxy S24 Ultra in your hands, you can unleash whole new levels of creativity, productivity and possibility.",
    "price": 129900,
    "discountPercentage": 7.7,
    "discountPrice": 119900,
    "rating": 4.8,
    "numReviews": 610,
    "stock": 22,
    "tag": "featured"
  },
  {
    "_id": "p3",
    "name": "OnePlus 12 (5G, Silky Black)",
    "brand": "OnePlus",
    "category": "Electronics",
    "subcategory": "Mobiles",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+12",
    "description": "Redefined flagship specs with Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera, and ultra-fast 100W SUPERVOOC charging.",
    "price": 79900,
    "discountPercentage": 12.5,
    "discountPrice": 69900,
    "rating": 4.7,
    "numReviews": 245,
    "stock": 30,
    "tag": "new-arrival"
  },
  {
    "_id": "p4",
    "name": "Google Pixel 8 Pro (128GB, Obsidian)",
    "brand": "Google",
    "category": "Electronics",
    "subcategory": "Mobiles",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+13",
    "description": "The all-pro phone engineered by Google. It has the best of Google AI, the most advanced Pixel Camera ever, and can help you do more, even faster.",
    "price": 99900,
    "discountPercentage": 10,
    "discountPrice": 89900,
    "rating": 4.6,
    "numReviews": 198,
    "stock": 18,
    "tag": "best-seller"
  },
  {
    "_id": "p5",
    "name": "Xiaomi Redmi Note 13 Pro+ (5G, Aurora Purple)",
    "brand": "Xiaomi",
    "category": "Electronics",
    "subcategory": "Mobiles",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+14",
    "description": "Capture greatness with the ultra-clear 200MP camera with OIS, 1.5K curved AMOLED display, and 120W HyperCharge.",
    "price": 44900,
    "discountPercentage": 11.1,
    "discountPrice": 39900,
    "rating": 4.5,
    "numReviews": 312,
    "stock": 40,
    "tag": "trending"
  },
  {
    "_id": "p6",
    "name": "Samsung Galaxy A55 (5G, Awesome Iceblue)",
    "brand": "Samsung",
    "category": "Electronics",
    "subcategory": "Mobiles",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+15",
    "description": "Premium glass back design, triple camera system with 50MP main sensor, and outstanding battery life for everyday performance.",
    "price": 39900,
    "discountPercentage": 12.5,
    "discountPrice": 34900,
    "rating": 4.4,
    "numReviews": 128,
    "stock": 25,
    "tag": "new-arrival"
  },
  {
    "_id": "p7",
    "name": "Nothing Phone (2) (256GB, Dark Gray)",
    "brand": "Nothing",
    "category": "Electronics",
    "subcategory": "Mobiles",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+16",
    "description": "A new way to interact. Features the iconic Glyph Interface, Nothing OS 2.0, dual 50MP cameras, and a gorgeous 6.7-inch flexible LTPO AMOLED display.",
    "price": 64900,
    "discountPercentage": 15.4,
    "discountPrice": 54900,
    "rating": 4.7,
    "numReviews": 182,
    "stock": 14,
    "tag": "trending"
  },
  {
    "_id": "p8",
    "name": "Motorola Edge 50 Pro (5G, Luxe Lavender)",
    "brand": "Motorola",
    "category": "Electronics",
    "subcategory": "Mobiles",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+17",
    "description": "Pantone Validated display and camera, vegan leather back, 125W TurboPower charging, and snapdragon 7 Gen 3 processor.",
    "price": 49900,
    "discountPercentage": 10,
    "discountPrice": 44900,
    "rating": 4.5,
    "numReviews": 95,
    "stock": 20,
    "tag": "new-arrival"
  },
  {
    "_id": "p9",
    "name": "MacBook Air M3 (13-inch, 8GB Unified Memory)",
    "brand": "Apple",
    "category": "Electronics",
    "subcategory": "Laptops",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+18",
    "description": "Supercharged by the next-generation M3 chip. Built for Apple Intelligence, featuring a silent fanless design and up to 18 hours of battery life.",
    "price": 109900,
    "discountPercentage": 9.1,
    "discountPrice": 99900,
    "rating": 4.9,
    "numReviews": 512,
    "stock": 10,
    "tag": "featured"
  },
  {
    "_id": "p10",
    "name": "Dell XPS 13 Plus (Core i7, 16GB RAM, 512GB SSD)",
    "brand": "Dell",
    "category": "Electronics",
    "subcategory": "Laptops",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+19",
    "description": "A sleek masterwork featuring borderless infinity display, haptic touchpad, capacitive function row, and Intel Evo performance.",
    "price": 149900,
    "discountPercentage": 13.3,
    "discountPrice": 129900,
    "rating": 4.5,
    "numReviews": 310,
    "stock": 8,
    "tag": "best-seller"
  },
  {
    "_id": "p11",
    "name": "HP Spectre x360 2-in-1 (Intel Core Ultra 7)",
    "brand": "HP",
    "category": "Electronics",
    "subcategory": "Laptops",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+20",
    "description": "Premium convertible design with immersive OLED touchscreen, intelligent AI camera, and supreme Bang & Olufsen sound.",
    "price": 159900,
    "discountPercentage": 9.4,
    "discountPrice": 144900,
    "rating": 4.7,
    "numReviews": 124,
    "stock": 7,
    "tag": "trending"
  },
  {
    "_id": "p12",
    "name": "Lenovo Yoga Slim 7x (Snapdragon X Elite)",
    "brand": "Lenovo",
    "category": "Electronics",
    "subcategory": "Laptops",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+21",
    "description": "Next-gen Copilot+ PC featuring exceptional Snapdragon battery life, PureSight 3K OLED screen, and advanced local AI processing.",
    "price": 119900,
    "discountPercentage": 8.3,
    "discountPrice": 109900,
    "rating": 4.6,
    "numReviews": 68,
    "stock": 12,
    "tag": "new-arrival"
  },
  {
    "_id": "p13",
    "name": "ASUS ROG Zephyrus G14 Gaming Laptop",
    "brand": "Asus",
    "category": "Electronics",
    "subcategory": "Laptops",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+22",
    "description": "Immersive gaming powerhouse with AMD Ryzen 9, NVIDIA RTX 4060 GPU, and beautiful ROG Nebula OLED HDR display.",
    "price": 159900,
    "discountPercentage": 12.5,
    "discountPrice": 139900,
    "rating": 4.8,
    "numReviews": 145,
    "stock": 9,
    "tag": "featured"
  },
  {
    "_id": "p14",
    "name": "Acer Swift Go 14 (OLED, Core i5)",
    "brand": "Acer",
    "category": "Electronics",
    "subcategory": "Laptops",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+23",
    "description": "Lightweight and powerful laptop featuring an exceptional 2.8K 90Hz OLED display, long battery life, and Intel Evo architecture.",
    "price": 74900,
    "discountPercentage": 13.4,
    "discountPrice": 64900,
    "rating": 4.4,
    "numReviews": 89,
    "stock": 15,
    "tag": "trending"
  },
  {
    "_id": "p15",
    "name": "Microsoft Surface Laptop 7 (Snapdragon X Plus)",
    "brand": "Microsoft",
    "category": "Electronics",
    "subcategory": "Laptops",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+24",
    "description": "Ultra-thin Copilot+ PC designed for the ultimate hybrid lifestyle. Up to 20 hours battery life with a gorgeous PixelSense touchscreen.",
    "price": 99900,
    "discountPercentage": 5,
    "discountPrice": 94900,
    "rating": 4.7,
    "numReviews": 42,
    "stock": 10,
    "tag": "new-arrival"
  },
  {
    "_id": "p16",
    "name": "Lenovo ThinkPad X1 Carbon Gen 12",
    "brand": "Lenovo",
    "category": "Electronics",
    "subcategory": "Laptops",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+25",
    "description": "The ultimate business laptop made of aerospace-grade carbon fiber. Featuring Intel Core Ultra vPro and legendary ThinkPad keyboard.",
    "price": 189900,
    "discountPercentage": 10.5,
    "discountPrice": 169900,
    "rating": 4.8,
    "numReviews": 76,
    "stock": 5,
    "tag": "best-seller"
  },
  {
    "_id": "p17",
    "name": "iPad Pro 11-inch (M4 Chip, 256GB Wi-Fi)",
    "brand": "Apple",
    "category": "Electronics",
    "subcategory": "Tablets",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+26",
    "description": "Impossibly thin design with Tandem OLED Liquid Retina XDR display, supercharged performance from Apple M4 chip.",
    "price": 99900,
    "discountPercentage": 5,
    "discountPrice": 94900,
    "rating": 4.9,
    "numReviews": 184,
    "stock": 12,
    "tag": "featured"
  },
  {
    "_id": "p18",
    "name": "Samsung Galaxy Tab S9 Ultra (256GB)",
    "brand": "Samsung",
    "category": "Electronics",
    "subcategory": "Tablets",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+27",
    "description": "Extraordinarily large 14.6-inch Dynamic AMOLED 2X screen with included S Pen. Dust and water-resistant premium metal casing.",
    "price": 119900,
    "discountPercentage": 12.5,
    "discountPrice": 104900,
    "rating": 4.8,
    "numReviews": 215,
    "stock": 10,
    "tag": "trending"
  },
  {
    "_id": "p19",
    "name": "iPad Air 11-inch (M2 Chip, 128GB)",
    "brand": "Apple",
    "category": "Electronics",
    "subcategory": "Tablets",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+28",
    "description": "Now available with M2 chip, a landscape front camera, and compatibility with the new Apple Pencil Pro.",
    "price": 59900,
    "discountPercentage": 8.3,
    "discountPrice": 54900,
    "rating": 4.7,
    "numReviews": 310,
    "stock": 25,
    "tag": "best-seller"
  },
  {
    "_id": "p20",
    "name": "Xiaomi Pad 6 (128GB, Gravity Gray)",
    "brand": "Xiaomi",
    "category": "Electronics",
    "subcategory": "Tablets",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+29",
    "description": "Best-in-class value tablet with Snapdragon 870, crisp 144Hz WQHD+ screen, and premium quad speakers.",
    "price": 34900,
    "discountPercentage": 14.3,
    "discountPrice": 29900,
    "rating": 4.6,
    "numReviews": 452,
    "stock": 35,
    "tag": "new-arrival"
  },
  {
    "_id": "p21",
    "name": "Apple Watch Series 9 (GPS, 45mm Aluminum)",
    "brand": "Apple",
    "category": "Electronics",
    "subcategory": "Smart Watches",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+30",
    "description": "Supercharged by the S9 SiP. Features Double Tap gesture, brighter always-on Retina display, and carbon neutral case options.",
    "price": 42900,
    "discountPercentage": 9.3,
    "discountPrice": 38900,
    "rating": 4.8,
    "numReviews": 564,
    "stock": 20,
    "tag": "best-seller"
  },
  {
    "_id": "p22",
    "name": "Samsung Galaxy Watch 6 Classic (47mm LTE)",
    "brand": "Samsung",
    "category": "Electronics",
    "subcategory": "Smart Watches",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+31",
    "description": "Return of the iconic rotating bezel. Track your body composition, monitor sleep coaching, and enjoy personalized heart zones.",
    "price": 39900,
    "discountPercentage": 12.5,
    "discountPrice": 34900,
    "rating": 4.6,
    "numReviews": 289,
    "stock": 18,
    "tag": "trending"
  },
  {
    "_id": "p23",
    "name": "Garmin Venu 3 Smartwatch (GPS, Slate)",
    "brand": "Garmin",
    "category": "Electronics",
    "subcategory": "Smart Watches",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+32",
    "description": "Ultimate health and fitness tracker with up to 14 days battery life, sleep coach, built-in speaker, and dynamic body battery score.",
    "price": 44900,
    "discountPercentage": 11.1,
    "discountPrice": 39900,
    "rating": 4.7,
    "numReviews": 143,
    "stock": 15,
    "tag": "featured"
  },
  {
    "_id": "p24",
    "name": "OnePlus Watch 2 (Smart Bluetooth WearOS)",
    "brand": "OnePlus",
    "category": "Electronics",
    "subcategory": "Smart Watches",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+33",
    "description": "Dual-Engine Architecture with Snapdragon W5 & BES2700. Delivers up to 100 hours of battery in smart WearOS mode.",
    "price": 29900,
    "discountPercentage": 16.7,
    "discountPrice": 24900,
    "rating": 4.5,
    "numReviews": 89,
    "stock": 22,
    "tag": "new-arrival"
  },
  {
    "_id": "p25",
    "name": "Canon EOS R5 Mirrorless Camera Body",
    "brand": "Canon",
    "category": "Electronics",
    "subcategory": "Cameras",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+34",
    "description": "Professional mirrorless camera with 45MP sensor, 8K video capture, 5-axis in-body image stabilization, and dual pixel autofocus.",
    "price": 349900,
    "discountPercentage": 8.6,
    "discountPrice": 319900,
    "rating": 4.9,
    "numReviews": 152,
    "stock": 4,
    "tag": "featured"
  },
  {
    "_id": "p26",
    "name": "Sony Alpha 7 IV Full-Frame Camera",
    "brand": "Sony",
    "category": "Electronics",
    "subcategory": "Cameras",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+35",
    "description": "The hybrid standard camera with 33MP Exmor R sensor, high-speed 4K 60p recording, and groundbreaking real-time eye tracking.",
    "price": 249900,
    "discountPercentage": 8,
    "discountPrice": 229900,
    "rating": 4.8,
    "numReviews": 284,
    "stock": 8,
    "tag": "best-seller"
  },
  {
    "_id": "p27",
    "name": "Fujifilm X-T5 Mirrorless Digital Camera",
    "brand": "Fujifilm",
    "category": "Electronics",
    "subcategory": "Cameras",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+36",
    "description": "Dial-based retro design featuring a 40.2MP high-resolution sensor, advanced 3-way tilting LCD screen, and signature film simulations.",
    "price": 169900,
    "discountPercentage": 5.9,
    "discountPrice": 159900,
    "rating": 4.7,
    "numReviews": 112,
    "stock": 6,
    "tag": "trending"
  },
  {
    "_id": "p28",
    "name": "Sony WH-1000XM5 Wireless Headphones",
    "brand": "Sony",
    "category": "Electronics",
    "subcategory": "Headphones",
    "image": "https://m.media-amazon.com/images/I/61+NGnL2EAL._AC_SL1500_.jpg",
    "description": "Industry-leading noise cancellation with Auto NC Optimizer, crystal clear hands-free calling, and up to 30 hours of quick-charge battery.",
    "price": 39900,
    "discountPercentage": 12.5,
    "discountPrice": 34900,
    "rating": 4.8,
    "numReviews": 1402,
    "stock": 25,
    "tag": "best-seller"
  },
  {
    "_id": "p29",
    "name": "Bose QuietComfort Ultra Over-Ear Headphones",
    "brand": "Bose",
    "category": "Electronics",
    "subcategory": "Headphones",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+38",
    "description": "Breakthrough spatialized audio for more immersive listening. World-class active noise cancellation with CustomTune technology.",
    "price": 42900,
    "discountPercentage": 11.7,
    "discountPrice": 37900,
    "rating": 4.7,
    "numReviews": 452,
    "stock": 15,
    "tag": "trending"
  },
  {
    "_id": "p30",
    "name": "Apple AirPods Max (Space Gray)",
    "brand": "Apple",
    "category": "Electronics",
    "subcategory": "Headphones",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+39",
    "description": "Apple-designed dynamic driver provides high-fidelity audio. Active Noise Cancellation blocks outside noise, so you can immerse yourself in music.",
    "price": 54900,
    "discountPercentage": 9.1,
    "discountPrice": 49900,
    "rating": 4.6,
    "numReviews": 928,
    "stock": 12,
    "tag": "featured"
  },
  {
    "_id": "p31",
    "name": "Sennheiser Accentum Wireless Headphones",
    "brand": "Sennheiser",
    "category": "Electronics",
    "subcategory": "Headphones",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+40",
    "description": "Unrivaled 50-hour battery life on a single charge. High-quality custom sound tuning and hybrid active noise cancellation.",
    "price": 17900,
    "discountPercentage": 16.8,
    "discountPrice": 14900,
    "rating": 4.5,
    "numReviews": 318,
    "stock": 35,
    "tag": "new-arrival"
  },
  {
    "_id": "p32",
    "name": "boAt Rockerz 450 Bluetooth On-Ear Headphone",
    "brand": "Boat",
    "category": "Electronics",
    "subcategory": "Headphones",
    "image": "https://m.media-amazon.com/images/I/51xxA+6E+xL._AC_SL1500_.jpg",
    "description": "Affordable wireless headphones with massive signature bass, up to 15 hours playback, and comfortable padded earcups.",
    "price": 4900,
    "discountPercentage": 20.4,
    "discountPrice": 3900,
    "rating": 4.2,
    "numReviews": 2405,
    "stock": 100,
    "tag": "best-seller"
  },
  {
    "_id": "p33",
    "name": "PlayStation 5 Console (Slim Edition)",
    "brand": "Sony",
    "category": "Electronics",
    "subcategory": "Gaming",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+42",
    "description": "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback and 3D Audio.",
    "price": 49900,
    "discountPercentage": 10,
    "discountPrice": 44900,
    "rating": 4.9,
    "numReviews": 1245,
    "stock": 15,
    "tag": "featured"
  },
  {
    "_id": "p34",
    "name": "Nintendo Switch (OLED Model)",
    "brand": "Nintendo",
    "category": "Electronics",
    "subcategory": "Gaming",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+43",
    "description": "Features a vibrant 7-inch OLED screen, a wide adjustable stand, a wired LAN port dock, and 64GB of internal storage.",
    "price": 34900,
    "discountPercentage": 8.3,
    "discountPrice": 31900,
    "rating": 4.8,
    "numReviews": 896,
    "stock": 20,
    "tag": "best-seller"
  },
  {
    "_id": "p35",
    "name": "Xbox Series X Console (1TB SSD)",
    "brand": "Microsoft",
    "category": "Electronics",
    "subcategory": "Gaming",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+44",
    "description": "The fastest, most powerful Xbox ever. Explore rich new worlds with 12 teraflops of raw graphic processing power and 4K gaming.",
    "price": 49900,
    "discountPercentage": 6,
    "discountPrice": 46900,
    "rating": 4.7,
    "numReviews": 412,
    "stock": 8,
    "tag": "trending"
  },
  {
    "_id": "p36",
    "name": "ASUS ROG Ally Handheld Gaming Console",
    "brand": "Asus",
    "category": "Electronics",
    "subcategory": "Gaming",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+45",
    "description": "A true Windows 11 handheld gaming device featuring AMD Ryzen Z1 Extreme processor and gorgeous 120Hz Full HD screen.",
    "price": 69900,
    "discountPercentage": 14.3,
    "discountPrice": 59900,
    "rating": 4.5,
    "numReviews": 215,
    "stock": 14,
    "tag": "new-arrival"
  },
  {
    "_id": "p37",
    "name": "Levi's Men's 511 Slim Fit Jeans",
    "brand": "Levi's",
    "category": "Fashion",
    "subcategory": "Men's Clothing",
    "image": "https://m.media-amazon.com/images/I/81p+zJ5sYVL._AC_UL1500_.jpg",
    "description": "A modern slim with room to move. The 511 Slim Fit Jeans are a classic since right now. These jeans are cut close to the body.",
    "price": 7900,
    "discountPercentage": 25.3,
    "discountPrice": 5900,
    "rating": 4.6,
    "numReviews": 1243,
    "stock": 50,
    "tag": "best-seller"
  },
  {
    "_id": "p38",
    "name": "Men's Premium Wool Blend Winter Coat",
    "brand": "UrbanStyle",
    "category": "Fashion",
    "subcategory": "Men's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+47",
    "description": "Sophisticated regular-fit long wool coat featuring notched lapels, button cuffs, and premium satin interior lining.",
    "price": 18900,
    "discountPercentage": 21.2,
    "discountPrice": 14900,
    "rating": 4.7,
    "numReviews": 110,
    "stock": 18,
    "tag": "featured"
  },
  {
    "_id": "p39",
    "name": "Puma Men's Essentials Fleece Hoodie",
    "brand": "Puma",
    "category": "Fashion",
    "subcategory": "Men's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+48",
    "description": "A classic pullover hoodie with Puma chest branding, cozy fleece-lined interior, and soft ribbed knit trims.",
    "price": 5500,
    "discountPercentage": 20,
    "discountPrice": 4400,
    "rating": 4.4,
    "numReviews": 654,
    "stock": 60,
    "tag": "trending"
  },
  {
    "_id": "p40",
    "name": "Adidas Originals Trefoil Tee",
    "brand": "Adidas",
    "category": "Fashion",
    "subcategory": "Men's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+49",
    "description": "Soft cotton jersey short sleeve shirt with the iconic oversized adidas trefoil logo screen-printed on the chest.",
    "price": 3000,
    "discountPercentage": 16.7,
    "discountPrice": 2500,
    "rating": 4.5,
    "numReviews": 954,
    "stock": 120,
    "tag": "new-arrival"
  },
  {
    "_id": "p41",
    "name": "Nike Dri-FIT Men's Training Shirts",
    "brand": "Nike",
    "category": "Fashion",
    "subcategory": "Men's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+50",
    "description": "Sweat-wicking lightweight fabric keeps you dry and cool throughout intensive cardio sessions and weight training.",
    "price": 3500,
    "discountPercentage": 14.3,
    "discountPrice": 3000,
    "rating": 4.7,
    "numReviews": 1145,
    "stock": 80,
    "tag": "best-seller"
  },
  {
    "_id": "p42",
    "name": "Women's Floral Summer Maxi Dress",
    "brand": "GlowClothing",
    "category": "Fashion",
    "subcategory": "Women's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+51",
    "description": "Flowy, breathable linen blend maxi dress featuring wrap V-neck style and elegant waist ties.",
    "price": 6900,
    "discountPercentage": 29,
    "discountPrice": 4900,
    "rating": 4.5,
    "numReviews": 320,
    "stock": 45,
    "tag": "trending"
  },
  {
    "_id": "p43",
    "name": "Levi's Women's High Rise Skinny Jeans",
    "brand": "Levi's",
    "category": "Fashion",
    "subcategory": "Women's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+52",
    "description": "Classic Levi's sculpting denim that hugs your curves. Crafted with a smart holding panel to flatten the stomach area.",
    "price": 8800,
    "discountPercentage": 21.6,
    "discountPrice": 6900,
    "rating": 4.6,
    "numReviews": 485,
    "stock": 32,
    "tag": "best-seller"
  },
  {
    "_id": "p44",
    "name": "Zara Silk Wrap V-Neck Blouse",
    "brand": "Zara",
    "category": "Fashion",
    "subcategory": "Women's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+53",
    "description": "Exquisite real mulberry silk long-sleeve blouse with a premium shawl collar, gathering side ties and elegant drape.",
    "price": 9900,
    "discountPercentage": 20.2,
    "discountPrice": 7900,
    "rating": 4.7,
    "numReviews": 89,
    "stock": 15,
    "tag": "featured"
  },
  {
    "_id": "p45",
    "name": "Puma Women's High Waist Gym Leggings",
    "brand": "Puma",
    "category": "Fashion",
    "subcategory": "Women's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+54",
    "description": "Squat-proof compression fit athletic wear utilizing DryCELL moisture control technology to keep you dry and comfortable.",
    "price": 4900,
    "discountPercentage": 18.4,
    "discountPrice": 4000,
    "rating": 4.4,
    "numReviews": 310,
    "stock": 55,
    "tag": "new-arrival"
  },
  {
    "_id": "p46",
    "name": "Nike Sportswear Club Women's Fleece Sweatpants",
    "brand": "Nike",
    "category": "Fashion",
    "subcategory": "Women's Clothing",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+55",
    "description": "An absolute essential loungewear. Combines a comfortable relaxed fit with a premium brushed fleece texture.",
    "price": 6000,
    "discountPercentage": 16.7,
    "discountPrice": 5000,
    "rating": 4.7,
    "numReviews": 642,
    "stock": 40,
    "tag": "best-seller"
  },
  {
    "_id": "p47",
    "name": "Kids Unisex Cotton Character Onesies",
    "brand": "Carter's",
    "category": "Fashion",
    "subcategory": "Kids Wear",
    "image": "https://m.media-amazon.com/images/I/71B9g+EONgL._AC_UX679_.jpg",
    "description": "Super soft 100% organic cotton baby onesies with snap-button bottom closure and cute embroidered cartoon hood detail.",
    "price": 3200,
    "discountPercentage": 25,
    "discountPrice": 2400,
    "rating": 4.8,
    "numReviews": 412,
    "stock": 90,
    "tag": "best-seller"
  },
  {
    "_id": "p48",
    "name": "Nike Kids Air Max Run Running Shoes",
    "brand": "Nike",
    "category": "Fashion",
    "subcategory": "Kids Wear",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+57",
    "description": "Kids lightweight performance running sneakers with active Air-Sole cushioning and velcro straps for easy adjustments.",
    "price": 6500,
    "discountPercentage": 15.4,
    "discountPrice": 5500,
    "rating": 4.6,
    "numReviews": 124,
    "stock": 35,
    "tag": "trending"
  },
  {
    "_id": "p49",
    "name": "Adidas Originals Kids Trefoil Tracksuit Set",
    "brand": "Adidas",
    "category": "Fashion",
    "subcategory": "Kids Wear",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+58",
    "description": "Iconic track jacket and matching elastic waist sweatpants featuring the famous 3-stripe side piping details.",
    "price": 7500,
    "discountPercentage": 20,
    "discountPrice": 6000,
    "rating": 4.7,
    "numReviews": 89,
    "stock": 25,
    "tag": "new-arrival"
  },
  {
    "_id": "p50",
    "name": "Nike Air Max 270 Responsive Running Shoes",
    "brand": "Nike",
    "category": "Fashion",
    "subcategory": "Shoes",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+59",
    "description": "Nike's first lifestyle Air Max brings you style, comfort and big attitude. Features a large responsive Air unit in the heel.",
    "price": 16000,
    "discountPercentage": 12.5,
    "discountPrice": 14000,
    "rating": 4.7,
    "numReviews": 2405,
    "stock": 45,
    "tag": "best-seller"
  },
  {
    "_id": "p51",
    "name": "Adidas Ultraboost Light Running Sneakers",
    "brand": "Adidas",
    "category": "Fashion",
    "subcategory": "Shoes",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+60",
    "description": "The lightest Ultraboost ever made. Experience epic energy return and absolute comfort from the Primeknit+ textile upper.",
    "price": 19000,
    "discountPercentage": 15.8,
    "discountPrice": 16000,
    "rating": 4.8,
    "numReviews": 932,
    "stock": 30,
    "tag": "featured"
  },
  {
    "_id": "p52",
    "name": "Puma Suede Classic XXI Sneakers",
    "brand": "Puma",
    "category": "Fashion",
    "subcategory": "Shoes",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+61",
    "description": "The classic low-top street silhouette featuring rich suede upper, signature Puma Formstrip, and robust rubber outsole.",
    "price": 7500,
    "discountPercentage": 20,
    "discountPrice": 6000,
    "rating": 4.5,
    "numReviews": 540,
    "stock": 50,
    "tag": "trending"
  },
  {
    "_id": "p53",
    "name": "Timberland Premium 6-Inch Waterproof Boot",
    "brand": "Timberland",
    "category": "Fashion",
    "subcategory": "Shoes",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+62",
    "description": "The original yellow waterproof boot. Crafted in premium nubuck leather with PrimaLoft eco-insulations.",
    "price": 19800,
    "discountPercentage": 10.1,
    "discountPrice": 17800,
    "rating": 4.7,
    "numReviews": 312,
    "stock": 15,
    "tag": "new-arrival"
  },
  {
    "_id": "p54",
    "name": "Samsonite Freeform Hardside Carry-On Spinner",
    "brand": "Samsonite",
    "category": "Fashion",
    "subcategory": "Bags",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+63",
    "description": "Extremely lightweight and durable polycarbonate hardshell luggage bag with double multi-directional spinner wheels.",
    "price": 19900,
    "discountPercentage": 20.1,
    "discountPrice": 15900,
    "rating": 4.8,
    "numReviews": 812,
    "stock": 25,
    "tag": "best-seller"
  },
  {
    "_id": "p55",
    "name": "Fjallraven Kanken Classic Everyday Backpack",
    "brand": "Fjallraven",
    "category": "Fashion",
    "subcategory": "Bags",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+64",
    "description": "Iconic Scandinavian everyday backpack made of dirt-resistant and water-resistant Vinylon F material.",
    "price": 9000,
    "discountPercentage": 11.1,
    "discountPrice": 8000,
    "rating": 4.6,
    "numReviews": 1243,
    "stock": 45,
    "tag": "trending"
  },
  {
    "_id": "p56",
    "name": "Michael Kors Jet Set Large Saffiano Leather Tote",
    "brand": "Michael Kors",
    "category": "Fashion",
    "subcategory": "Bags",
    "image": "https://m.media-amazon.com/images/I/71D9ImsvEtL._AC_UY695_.jpg",
    "description": "Sophisticated structured handbag crafted in cross-grain saffiano leather with polished gold-tone hardware detailing.",
    "price": 24800,
    "discountPercentage": 20.2,
    "discountPrice": 19800,
    "rating": 4.7,
    "numReviews": 184,
    "stock": 12,
    "tag": "featured"
  },
  {
    "_id": "p57",
    "name": "Instant Pot Duo Plus 9-in-1 Pressure Cooker",
    "brand": "Instant Pot",
    "category": "Home & Kitchen",
    "subcategory": "Home & Kitchen",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+66",
    "description": "Electric pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, sterilizer, and sous vide setup.",
    "price": 14900,
    "discountPercentage": 13.4,
    "discountPrice": 12900,
    "rating": 4.8,
    "numReviews": 2405,
    "stock": 30,
    "tag": "best-seller"
  },
  {
    "_id": "p58",
    "name": "Keurig K-Elite Single Serve Coffee Maker",
    "brand": "Keurig",
    "category": "Home & Kitchen",
    "subcategory": "Home & Kitchen",
    "image": "https://m.media-amazon.com/images/I/61k6Z+N0TKL._AC_SL1500_.jpg",
    "description": "Premium single-cup pod brewer with strong brew options, iced coffee settings, and custom hot water dispensing controls.",
    "price": 18900,
    "discountPercentage": 15.9,
    "discountPrice": 15900,
    "rating": 4.6,
    "numReviews": 932,
    "stock": 20,
    "tag": "trending"
  },
  {
    "_id": "p59",
    "name": "Dyson V11 Absolute Cordless Vacuum Cleaner",
    "brand": "Dyson",
    "category": "Home & Kitchen",
    "subcategory": "Home & Kitchen",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+68",
    "description": "Intelligently optimizes suction and run time across all floor types. Advanced whole-machine filtration traps 99.99% of dust particles.",
    "price": 69900,
    "discountPercentage": 14.3,
    "discountPrice": 59900,
    "rating": 4.8,
    "numReviews": 456,
    "stock": 10,
    "tag": "featured"
  },
  {
    "_id": "p60",
    "name": "Philips Premium Airfryer XXL with Fat Removal",
    "brand": "Philips",
    "category": "Home & Kitchen",
    "subcategory": "Home & Kitchen",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+69",
    "description": "The only airfryer with fat removal technology that extracts and captures excess fat, delivering crispy fried food with 90% less oil.",
    "price": 29900,
    "discountPercentage": 16.7,
    "discountPrice": 24900,
    "rating": 4.7,
    "numReviews": 312,
    "stock": 18,
    "tag": "new-arrival"
  },
  {
    "_id": "p61",
    "name": "Advanced Night Repair Synchronized Multi-Recovery",
    "brand": "Estee Lauder",
    "category": "Beauty",
    "subcategory": "Beauty",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+70",
    "description": "Patented deep-penetrating face serum that significantly reduces the look of multiple signs of skin aging caused by environmental assaults.",
    "price": 12500,
    "discountPercentage": 20.8,
    "discountPrice": 9900,
    "rating": 4.8,
    "numReviews": 1243,
    "stock": 40,
    "tag": "best-seller"
  },
  {
    "_id": "p62",
    "name": "Dior Sauvage Eau de Parfum Spray (100ml)",
    "brand": "Dior",
    "category": "Beauty",
    "subcategory": "Beauty",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+71",
    "description": "An absolute legend. Powerful and noble composition blending reggio calabria bergamot, papua new guinean vanilla absolute and precious amberwood.",
    "price": 14500,
    "discountPercentage": 10.3,
    "discountPrice": 13000,
    "rating": 4.9,
    "numReviews": 2402,
    "stock": 25,
    "tag": "trending"
  },
  {
    "_id": "p63",
    "name": "Clinique Moisture Surge 100H Hydrator",
    "brand": "Clinique",
    "category": "Beauty",
    "subcategory": "Beauty",
    "image": "https://m.media-amazon.com/images/I/61S7PBB9g9L._SL1500_.jpg",
    "description": "Oil-free gel-cream moisturizer with exclusive aloe bio-ferment and hyaluronic acid that penetrates deep, lasting for 100 hours.",
    "price": 4600,
    "discountPercentage": 15.2,
    "discountPrice": 3900,
    "rating": 4.6,
    "numReviews": 541,
    "stock": 50,
    "tag": "featured"
  },
  {
    "_id": "p64",
    "name": " Dyson Airwrap Multi-Styler Complete Long",
    "brand": "Dyson",
    "category": "Beauty",
    "subcategory": "Beauty",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+73",
    "description": "Curling, shaping, smoothing, and hiding flyaways using the Coanda effect – with no extreme heat damage to hair.",
    "price": 59900,
    "discountPercentage": 8.3,
    "discountPrice": 54900,
    "rating": 4.7,
    "numReviews": 312,
    "stock": 12,
    "tag": "new-arrival"
  },
  {
    "_id": "p65",
    "name": "Fitbit Charge 6 Advanced Fitness Tracker",
    "brand": "Fitbit",
    "category": "Sports",
    "subcategory": "Sports",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+74",
    "description": "Features built-in GPS, continuous heart rate tracking, smart sleep coaching, stress management tools, and Google Maps integrations.",
    "price": 15900,
    "discountPercentage": 18.9,
    "discountPrice": 12900,
    "rating": 4.5,
    "numReviews": 284,
    "stock": 35,
    "tag": "best-seller"
  },
  {
    "_id": "p66",
    "name": "Wilson Evolution Indoor Game Basketball",
    "brand": "Wilson",
    "category": "Sports",
    "subcategory": "Sports",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+75",
    "description": "The preferred indoor high school match basketball, featuring a micro-fiber composite leather cover and signature laid-in channels.",
    "price": 7900,
    "discountPercentage": 12.7,
    "discountPrice": 6900,
    "rating": 4.8,
    "numReviews": 1243,
    "stock": 60,
    "tag": "trending"
  },
  {
    "_id": "p67",
    "name": "Spalding NBA Slam Jam Mini Basketball Hoop",
    "brand": "Spalding",
    "category": "Sports",
    "subcategory": "Sports",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+76",
    "description": "Over-the-door home or office mini basketball set with steel breakaway rim, padded backboard, and a mini rubber basketball.",
    "price": 4500,
    "discountPercentage": 22.2,
    "discountPrice": 3500,
    "rating": 4.4,
    "numReviews": 893,
    "stock": 40,
    "tag": "featured"
  },
  {
    "_id": "p68",
    "name": "Hydro Flask Wide Mouth Straw Lid Bottle (32oz)",
    "brand": "Hydro Flask",
    "category": "Sports",
    "subcategory": "Sports",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+77",
    "description": "TempShield double-wall vacuum insulation keeps drinks cold up to 24 hours. Crafted in durable professional-grade stainless steel.",
    "price": 4400,
    "discountPercentage": 11.4,
    "discountPrice": 3900,
    "rating": 4.7,
    "numReviews": 1482,
    "stock": 75,
    "tag": "new-arrival"
  },
  {
    "_id": "p69",
    "name": "Atomic Habits by James Clear (Hardcover)",
    "brand": "Penguin Books",
    "category": "Books",
    "subcategory": "Books",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+78",
    "description": "An easy & proven way to build good habits & break bad ones. The definitive guide to optimization and compounding daily self-improvements.",
    "price": 2700,
    "discountPercentage": 29.6,
    "discountPrice": 1900,
    "rating": 4.9,
    "numReviews": 5410,
    "stock": 150,
    "tag": "best-seller"
  },
  {
    "_id": "p70",
    "name": "The Creative Act: A Way of Being by Rick Rubin",
    "brand": "Penguin Press",
    "category": "Books",
    "subcategory": "Books",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+79",
    "description": "A beautiful, gentle, and deep workbook of wisdom that illuminates the pathway of unlocking creative potential for everyone.",
    "price": 3200,
    "discountPercentage": 21.9,
    "discountPrice": 2500,
    "rating": 4.8,
    "numReviews": 612,
    "stock": 80,
    "tag": "trending"
  },
  {
    "_id": "p71",
    "name": "The Psychology of Money by Morgan Housel",
    "brand": "Harriman House",
    "category": "Books",
    "subcategory": "Books",
    "image": "https://m.media-amazon.com/images/I/71g2ednj0JL._AC_UY327_FMwebp_QL65_.jpg",
    "description": "Timeless lessons on wealth, greed, and happiness. Morgan shares 19 short stories exploring the strange ways people think about money.",
    "price": 2000,
    "discountPercentage": 25,
    "discountPrice": 1500,
    "rating": 4.7,
    "numReviews": 1843,
    "stock": 120,
    "tag": "featured"
  },
  {
    "_id": "p72",
    "name": "Anker Prime 20,000mAh Power Bank (200W)",
    "brand": "Anker",
    "category": "Accessories",
    "subcategory": "Accessories",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+81",
    "description": "Ultra-high capacity external battery with 200W multi-device fast charging output and intelligent smart screen monitor display.",
    "price": 12900,
    "discountPercentage": 15.5,
    "discountPrice": 10900,
    "rating": 4.8,
    "numReviews": 412,
    "stock": 45,
    "tag": "best-seller"
  },
  {
    "_id": "p73",
    "name": "Apple AirTag (4 Pack)",
    "brand": "Apple",
    "category": "Accessories",
    "subcategory": "Accessories",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+82",
    "description": "Keep track of and find your keys, wallet, luggage, and backpacks inside the Find My app. Simple one-tap setup connects with your iPhone.",
    "price": 9900,
    "discountPercentage": 10.1,
    "discountPrice": 8900,
    "rating": 4.7,
    "numReviews": 2435,
    "stock": 90,
    "tag": "trending"
  },
  {
    "_id": "p74",
    "name": "Logitech MX Master 3S Wireless Mouse",
    "brand": "Logitech",
    "category": "Accessories",
    "subcategory": "Accessories",
    "image": "https://placehold.co/500x500/eeeeee/999999?text=Product+83",
    "description": "Legendary ergonomic performance mouse featuring 8K DPI any-surface tracking, quiet clicks, and MagSpeed electromagnetic scrolling.",
    "price": 9900,
    "discountPercentage": 5.1,
    "discountPrice": 9400,
    "rating": 4.8,
    "numReviews": 1243,
    "stock": 60,
    "tag": "featured"
  }
];

export const reviews = [
  {
    id: 1,
    name: 'Sarah Jenkins',
    avatar: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg',
    rating: 5,
    comment: 'Exceptional service and quick delivery! The headphones sound absolutely incredible, and the packaging was robust. Highly recommend ShopEZ.'
  },
  {
    id: 2,
    name: 'Marcus Chen',
    avatar: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg',
    rating: 5,
    comment: 'Buying the new iPhone was so easy. The customer support answered my questions about warranty instantly. A truly premium MERN platform.'
  },
  {
    id: 3,
    name: 'Emily Rodriguez',
    avatar: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg',
    rating: 4,
    comment: 'The Nike shoes are original and extremely comfortable. The discount price here was better than other online retail sites. Very satisfied.'
  }
];
