import { 
  FaLaptop, 
  FaMobileAlt, 
  FaTv, 
  FaTshirt, 
  FaRunning, 
  FaCouch, 
  FaGem, 
  FaHeartbeat,
  FaBookOpen
} from 'react-icons/fa';

export const categories = [
  {
    id: 'electronics',
    name: 'Electronics',
    icon: FaLaptop,
    image: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg',
    path: '/products?category=electronics'
  },
  {
    id: 'fashion',
    name: 'Fashion',
    icon: FaTshirt,
    image: 'https://m.media-amazon.com/images/I/61Nl8q4lV2L._AC_UL1500_.jpg',
    path: '/products?category=fashion'
  },
  {
    id: 'footwear',
    name: 'Footwear',
    icon: FaRunning,
    image: 'https://m.media-amazon.com/images/I/71D9ImsvEtL._AC_UY695_.jpg',
    path: '/products?category=footwear'
  },
  {
    id: 'home-kitchen',
    name: 'Home & Kitchen',
    icon: FaCouch,
    image: 'https://m.media-amazon.com/images/I/81BDBKkQ4AL._AC_SL1500_.jpg',
    path: '/products?category=home-kitchen'
  },
  {
    id: 'sports',
    name: 'Sports',
    icon: FaRunning,
    image: 'https://m.media-amazon.com/images/I/71Xm3Q+-l+L._AC_SL1500_.jpg',
    path: '/products?category=sports'
  }
];

export const products = [
  {
    name: "Apple iPhone 16 Pro (256GB, Natural Titanium)",
    description: "The ultimate iPhone featuring a stunning 6.3-inch Super Retina XDR display, A18 Pro chip for unparalleled gaming performance, and a pro camera system with 48MP main camera and 5x optical zoom.",
    price: 119900,
    discountPercentage: 8,
    discountPrice: 110308,
    category: "Electronics",
    subcategory: "Phones",
    brand: "Apple",
    image: "https://m.media-amazon.com/images/I/81+GIkwqLIL._AC_SL1500_.jpg",
    stock: 45,
    rating: 4.9,
    numReviews: 1850,
    tag: "featured",
    bestSeller: false,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "Samsung Galaxy S25 Ultra (512GB, Titanium Gray)",
    description: "Welcome to the era of mobile AI. The Galaxy S25 Ultra features a massive 6.8-inch Dynamic AMOLED display, a built-in S-Pen, and a revolutionary 200MP quad-telephoto camera system.",
    price: 139900,
    discountPercentage: 10,
    discountPrice: 125910,
    category: "Electronics",
    subcategory: "Phones",
    brand: "Samsung",
    image: "https://m.media-amazon.com/images/I/71cx1JzXj1L._AC_SL1500_.jpg",
    stock: 38,
    rating: 4.8,
    numReviews: 1245,
    tag: "trending",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: true
  },
  {
    name: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    description: "Industry-leading noise cancellation optimized for you. Enjoy up to 30 hours of battery life, crystal clear hands-free calling, and exceptional audio quality with the new Integrated Processor V1.",
    price: 34900,
    discountPercentage: 15,
    discountPrice: 29665,
    category: "Electronics",
    subcategory: "Audio",
    brand: "Sony",
    image: "https://m.media-amazon.com/images/I/61+NGnL2EAL._AC_SL1500_.jpg",
    stock: 120,
    rating: 4.7,
    numReviews: 4500,
    tag: "best-seller",
    bestSeller: true,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "Canon EOS R5 Mirrorless Camera Body",
    description: "Professional mirrorless camera with a 45MP full-frame CMOS sensor, 8K raw video recording capability, 5-axis in-body image stabilization, and cutting-edge Dual Pixel CMOS AF II.",
    price: 339900,
    discountPercentage: 5,
    discountPrice: 322905,
    category: "Electronics",
    subcategory: "Cameras",
    brand: "Canon",
    image: "https://m.media-amazon.com/images/I/7112S+2uLUL._AC_SL1500_.jpg",
    stock: 12,
    rating: 4.8,
    numReviews: 760,
    tag: "featured",
    bestSeller: false,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "Garmin Venu 3 Smartwatch (GPS, Slate)",
    description: "Purpose-built advanced health and fitness smartwatch. Includes up to 14 days of battery life, built-in speaker and microphone, advanced sleep coach, and wheelchair mode.",
    price: 44900,
    discountPercentage: 12,
    discountPrice: 39512,
    category: "Electronics",
    subcategory: "Smart Watches",
    brand: "Garmin",
    image: "https://m.media-amazon.com/images/I/61kYQGz4g9L._AC_SL1500_.jpg",
    stock: 25,
    rating: 4.6,
    numReviews: 87,
    tag: "new-arrival",
    bestSeller: false,
    featured: false,
    newArrival: true,
    trending: false
  },
  {
    name: "Apple MacBook Air M3 (13-inch, 8GB RAM, 256GB SSD)",
    description: "Supercharged by the M3 chip. The incredibly thin and light MacBook Air features a silent, fanless design, up to 18 hours of battery life, and a brilliant Liquid Retina display.",
    price: 109900,
    discountPercentage: 9,
    discountPrice: 100009,
    category: "Electronics",
    subcategory: "Laptops",
    brand: "Apple",
    image: "https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg",
    stock: 55,
    rating: 4.9,
    numReviews: 3200,
    tag: "best-seller",
    bestSeller: true,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "PlayStation 5 Console (Slim Edition)",
    description: "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games.",
    price: 49900,
    discountPercentage: 10,
    discountPrice: 44910,
    category: "Electronics",
    subcategory: "Gaming",
    brand: "Sony",
    image: "https://m.media-amazon.com/images/I/51r2X3y973L._AC_SL1500_.jpg",
    stock: 74,
    rating: 4.9,
    numReviews: 8900,
    tag: "trending",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: true
  },
  {
    name: "Nike Air Max 270 Men's Running Shoes",
    description: "Legendary Air meets exceptional comfort. The Nike Air Max 270 delivers visible cushioning under every step. Updated for modern comfort, it nods to the original with its exaggerated tongue top and heritage tongue logo.",
    price: 12900,
    discountPercentage: 20,
    discountPrice: 10320,
    category: "Footwear",
    subcategory: "Shoes",
    brand: "Nike",
    image: "https://m.media-amazon.com/images/I/71D9ImsvEtL._AC_UY695_.jpg",
    stock: 150,
    rating: 4.5,
    numReviews: 245,
    tag: "best-seller",
    bestSeller: true,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "Levi's Men's 511 Slim Fit Jeans",
    description: "A modern slim with room to move. The 511 Slim Fit Jeans are a classic since right now. These jeans sit below the waist with a slim fit from hip to ankle. Crafted with water<less> technology.",
    price: 3900,
    discountPercentage: 25,
    discountPrice: 2925,
    category: "Fashion",
    subcategory: "Men",
    brand: "Levi's",
    image: "https://m.media-amazon.com/images/I/81p+zJ5sYVL._AC_UL1500_.jpg",
    stock: 85,
    rating: 4.3,
    numReviews: 512,
    tag: "none",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "Bose QuietComfort Ultra Over-Ear Headphones",
    description: "Breakthrough spatialized audio for more immersive listening. World-class active noise cancellation with CustomTune technology that auto-adjusts the sound to your ears' shape.",
    price: 42900,
    discountPercentage: 11,
    discountPrice: 38181,
    category: "Electronics",
    subcategory: "Audio",
    brand: "Bose",
    image: "https://m.media-amazon.com/images/I/51rP+8O49PL._AC_SL1500_.jpg",
    stock: 32,
    rating: 4.7,
    numReviews: 310,
    tag: "featured",
    bestSeller: false,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "Adidas Ultraboost Light Running Sneakers",
    description: "Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. The magic lies in the Light BOOST midsole, a new generation of adidas BOOST.",
    price: 18900,
    discountPercentage: 30,
    discountPrice: 13230,
    category: "Footwear",
    subcategory: "Shoes",
    brand: "Adidas",
    image: "https://m.media-amazon.com/images/I/71lD844lq3L._AC_UY695_.jpg",
    stock: 40,
    rating: 4.6,
    numReviews: 185,
    tag: "new-arrival",
    bestSeller: false,
    featured: false,
    newArrival: true,
    trending: false
  },
  {
    name: "Dell XPS 15 (OLED, Core i9, 32GB RAM)",
    description: "A sleek masterwork featuring a borderless 3.5K OLED infinity display, massive 86Wh battery, and immense creative power from the Intel Core i9 processor and NVIDIA RTX 4070 GPU.",
    price: 249900,
    discountPercentage: 15,
    discountPrice: 212415,
    category: "Electronics",
    subcategory: "Laptops",
    brand: "Dell",
    image: "https://m.media-amazon.com/images/I/71c5W9NxN5L._AC_SL1500_.jpg",
    stock: 8,
    rating: 4.8,
    numReviews: 115,
    tag: "featured",
    bestSeller: false,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "OnePlus 12 (16GB RAM, 512GB, Flowy Emerald)",
    description: "Redefined flagship specs with Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera for Mobile, and ultra-fast 100W SUPERVOOC charging combined with a massive 5400mAh battery.",
    price: 69900,
    discountPercentage: 10,
    discountPrice: 62910,
    category: "Electronics",
    subcategory: "Phones",
    brand: "OnePlus",
    image: "https://m.media-amazon.com/images/I/717QSlK-GTL._AC_SL1500_.jpg",
    stock: 65,
    rating: 4.7,
    numReviews: 850,
    tag: "trending",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: true
  },
  {
    name: "Puma Women's High Waist Gym Leggings",
    description: "Squat-proof compression fit athletic wear utilizing DryCELL moisture control technology to keep you dry and comfortable during intense workout sessions.",
    price: 3500,
    discountPercentage: 40,
    discountPrice: 2100,
    category: "Fashion",
    subcategory: "Women",
    brand: "Puma",
    image: "https://m.media-amazon.com/images/I/51r2t4hV+jL._AC_UY879_.jpg",
    stock: 110,
    rating: 4.5,
    numReviews: 420,
    tag: "best-seller",
    bestSeller: true,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "Google Pixel 8 Pro (256GB, Obsidian)",
    description: "The all-pro phone engineered by Google. It has the best of Google AI, the most advanced Pixel Camera ever, and can help you do more, even faster with the Tensor G3 chip.",
    price: 106900,
    discountPercentage: 15,
    discountPrice: 90865,
    category: "Electronics",
    subcategory: "Phones",
    brand: "Google",
    image: "https://m.media-amazon.com/images/I/71B4hJ7C9mL._AC_SL1500_.jpg",
    stock: 22,
    rating: 4.6,
    numReviews: 310,
    tag: "none",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: false
  }
];
